version: "3.9"
networks:
  counter-image-dev:
    driver: bridge
services:
  app:
    image: docker.io/library/counter-image
    container_name: counter-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    networks:
      - counter-image-dev
    depends_on:
      - postgres_db
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres_db;Port=5432;Database=ProjectDataBase2; User Id=postgres;Password=123457;TrustServerCertificate=True;Pooling=true;
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123457
      POSTGRES_DB: ProjectDataBase2
    ports:
      - "5433:5432"
    restart: always
    networks:
      - counter-image-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: