
stages:
  - build
  - deploy

alpine-deploy:
  stage: build
  image: counter-image
  variables:
    DOCKER_BUILDKIT: 1
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 
  script:
    - docker build --pull -t hub.66bit.ru/shared/images/alpine-deploy:3.17.2 -f alpine-deploy-3.17.2/Dockerfile .
    - docker push hub.66bit.ru/shared/images/alpine-deploy:3.17.2
  after_script:
    - docker logout $CI_REGISTRY
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual


